// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://torqbmnzwfwmylmfxfhn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvcnFibW56d2Z3bXlsbWZ4ZmhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5OTIyNTMsImV4cCI6MjA2NjU2ODI1M30.MgljG-uwzk2oAmEpfY2YyYjoBLNH3mEwm6a8b-Sy2TQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);